#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

dependency "git-lfs"

function main() {

  # Git LFS
  command -v git-lfs >/dev/null 2>&1 || {
    echo >&2 "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit."
    exit 2
  }
  git lfs post-commit "$@"

}

main "$@"
