#!/usr/bin/env bash

export BOILERPLATE_NO_COLOR="true"

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  "./pipeline/lint-staged"

}

main "$@"
