#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Cleaning...${NO_COLOR}"

  (
    set -x

    git remote remove "zboilerplate" 2>/dev/null || true

    rm -rf "./build"
    rm -rf "./node_modules"
  )

}

main "$@"
