#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  local PRODUCTION="false"
  if [[ "$*" == *"--production"* ]]; then
    PRODUCTION="true"
  fi

  echo -e "${OK_COLOR}==> Installing dependencies..."

  NPM="$(command -v npm)"

  (
    set -x
    # "--unsafe-perm" is required, else postinstall won't run during Docker build
    "${NPM}" install \
      --unsafe-perm \
      "$@"
  )

  if [[ "${PRODUCTION}" != "true" ]]; then
    (
      set -x
      "${NPM}" audit fix || true
    )
  fi

}

main "$@"
