#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

function main() {

  local COMMAND="${1}"
  shift

  BOILERPLATE_LOG_TIME="false" \
    "${COMMAND}" "$@"

}

main "$@"
